

networks:
  neo4j-internal:
  
services:
  neo4j_server1:
    image: neo4j:latest
    hostname: neo4j_server1
    networks:
      neo4j-internal:
        aliases:
          - neo4j-network
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data/server1:/data
      - ./neo4j/logs/server1:/logs
      - ./neo4j/conf/server1:/conf
      - ./neo4j/import/server1:/import
      - ./neo4j/neo4j.conf:/conf/neo4j.conf
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/ZiGOvich268
      - NEO4J_EDITION=docker_compose
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_server_config_strict__validation_enabled=false
    user: 0:0

  neo4j_server2:
    image: neo4j:latest
    hostname: neo4j_server2
    networks:
      neo4j-internal:
        aliases:
          - neo4j-network
    ports:
      - "7475:7474"
      - "7688:7687"
    volumes:
      - ./neo4j/data/server2:/data
      - ./neo4j/logs/server2:/logs
      - ./neo4j/conf/server2:/conf
      - ./neo4j/import/server2:/import
      - ./neo4j/neo4j.conf:/conf/neo4j.conf
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/ZiGOvich268
      - NEO4J_EDITION=docker_compose
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_server_config_strict__validation_enabled=false
    user: 0:0

  neo4j_server3:
    image: neo4j:latest
    hostname: neo4j_server3
    networks:
      neo4j-internal:
        aliases:
          - neo4j-network
    ports:
      - "7476:7474"
      - "7689:7687"
    volumes:
      - ./neo4j/data/server3:/data
      - ./neo4j/logs/server3:/logs
      - ./neo4j/conf/server3:/conf
      - ./neo4j/import/server3:/import
      - ./neo4j/neo4j.conf:/conf/neo4j.conf
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/ZiGOvich268
      - NEO4J_EDITION=docker_compose
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_server_config_strict__validation_enabled=false
    user: 0:0